// Generated by Selenium IDE
import Calculator.CalculatorPage;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.WebDriver;

import static org.junit.Assert.assertEquals;
public class CalculatorTest {
  private WebDriver driver;
  CalculatorPage calculatorPage;

  @Before
  public void setUp() {
    calculatorPage = new CalculatorPage();

  }

  @Test
  public void calculate_Div10Div2_Result5() {
    String actual = calculatorPage.calculate("10/2=");
    String expected = "5";
    assertEquals(actual,expected);
  }

  @Test
  public void calculate_Add5p2p20p100p1000_Result_1127() {
    String actual = calculatorPage.calculate("5+2+20+100+1000=");
    String expected = "1127";
    assertEquals(actual,expected);
  }

  @Test
  public void calculate_Div544Div0_Result_Infinity() {
    String actual = calculatorPage.calculate("544/0=");
    String expected = "Infinity";
    assertEquals(actual,expected);
  }

  @Test
  public void calculate_Multi540times0_Result0() {
    String actual = calculatorPage.calculate("540*0=");
    String expected = "0";
    assertEquals(actual,expected);

  }

  //Bug this should be 52
  @Test
  public void calculate_Multi5x2x05dot2_Result52() {
    String actual = calculatorPage.calculate("5x2x05.2=");
    String expected = "52";
    assertEquals(actual,expected);
  }

  @Test
  public void calculate_MultiAndDive64times2div32_Result4() {
    String actual = calculatorPage.calculate("64*2/32=");
    String expected = "4";
    assertEquals(actual,expected);
  }

  @Test
  public void calculate_Multi999999999p999999999_Result999999998000000000() {
    String actual = calculatorPage.calculate("999999999*999999999=");
    String expected = "999999998000000000";
    assertEquals(actual,expected);
  }

  @Test
  public void calculate_Subtract10minus100dot10_ResultNegative90dot1() {
    String actual = calculatorPage.calculate("10-100.10=");
    String expected = "-90.1";
    assertEquals(actual,expected);
  }

  //bug this should calculate -10*-20=200
  @Test
  public void calculate_MultiMinus10TimesMinus20_Result200() {
    String actual = calculatorPage.calculate("-10*-20=");
    String expected = "200";
    assertEquals(actual, expected);
  }

  //bug this should calculate -10/-2=200
  @Test
  public void calculate_DivMinus10TimesMinus20_Result200() {
    String actual = calculatorPage.calculate("-10/-2=");
    String expected = "5";
    assertEquals(actual, expected);
  }

  @Test
  public void calculate_MultiMinus10times20times2dot5_Result200() {
    String actual = calculatorPage.calculate("-10*20*2.5=");
    String expected = "-500";
    assertEquals(actual, expected);
  }

  @Test
  public void calculate_Multi0Dot000004Times2_Result0dot0000008() {
    String actual = calculatorPage.calculate("0.000004*2=");
    String expected = "0.000008";
    assertEquals(actual, expected);
  }
  
}
